---
- name: Aprovicionamiento Servidor
  become: yes
  hosts: test
  #Esta es la ruta del archivo con la lista
  vars_files:
    - user_lists.yml
  vars:
    pwd: "Ponga_la_pwd"
  tasks:

  - name: Crea grupo usuarios
    ansible.builtin.group:
      name: soporte
      state: present
      gid: 1001

  - name: Crea usuarios
    ansible.builtin.user:
      name: "{{ item.name }}"
      comment: "{{ item.comment  }}"
      state: present
      group: "{{ item.group }}"
      password: "{{ pwd | password_hash('sha512') }}"
    loop: "{{ users }}"
  #seccion con chage
  - name: ejecuta shell chage
    ansible.builtin.shell: chage -d0 "{{ item.name }}"
    args:
      executable: /bin/bash
    loop: "{{ users }}"

  - name: backup de sudoers
    ansible.builtin.copy:
      src: /etc/sudoers
      dest: /etc/sudoers_{{ansible_date_time.date}}.bck
      mode: 0440

  - name: Sincroniza sudoers
    ansible.builtin.copy:
      src: /root/Playbooks/files/sudoers
      dest: /etc/sudoers

  - name: Agrega permisos geo
    ansible.builtin.copy:
      src: /root/Playbooks/files/binarios_geo.sh
      dest: /etc/profile.d/

  - name: Permiso a sudo
    ansible.builtin.file:
      path: /usr/bin/sudo
      owner: root
      group: root
      mode: '4755'

  - name: Transferencia de banner
    ansible.builtin.copy:
      src: /root/Playbooks/files/login_banner
      dest: /etc/ssh/

  - name: Modulo shell echo
    ansible.builtin.shell: echo "Banner /etc/ssh/login_banner" >> /etc/ssh/sshd_config

  - name: restart servicio
    ansible.builtin.service:
      name: sshd
      state: restarted
