---
- name: crea usuarios
  become: yes
  hosts: test
  #Esta es la ruta del archivo con la lista
  vars_files: 
    - user_lists.yml
  tasks:
  - name: Crea usuarios
    ansible.builtin.user:
      #se utiliza la palabra clave "item" con "name" del user_list.yml
      name: "{{ item.name }}"
      comment: "Usuario de Soporte"
      state: present
      group: "soporte"
    loop: "{{ users }}"
      
      
